### ISSUE TITLE
Invalid key: preSignUpHook

### ISSUE THREAD

**Issue by ilrein** [studiointeract/accounts-ui#10]
Looks like this particular hook is breaking the package. If you try to add it in your config:

```
Accounts.ui.config({
  passwordSignupFields: 'EMAIL_ONLY',
  loginPath: '/',
  onSignedInHook: () => FlowRouter.go('/dashboard'),
  onSignedOutHook: () => FlowRouter.go('/'),
  preSignUpHook: () => { console.log('hello') }
});
```

You get an error of:
```Uncaught Error: Accounts.ui.config: Invalid key: preSignUpHook```

If you take it out:

```
Accounts.ui.config({
  passwordSignupFields: 'EMAIL_ONLY',
  loginPath: '/',
  onSignedInHook: () => FlowRouter.go('/dashboard'),
  onSignedOutHook: () => FlowRouter.go('/'),
  // preSignUpHook: () => { console.log('hello') }
});
```

You get an error of:
```Uncaught TypeError: _accountsBase.Accounts.ui._options.preSignUpHook is not a function```

**Comment by Morganjackson** [comment]
I'm seeing the same thing.

**Comment by timbrandin** [comment]
Alright, I'm on it

**Comment by timbrandin** [comment]
d5aa60e solves this, a new release in on the way.

**Comment by xavcz** [comment]
I'm 10 minutes late! I saw this too :sweat_smile:

**Comment by timbrandin** [comment]
release-1.1.1 is out
