### ISSUE TITLE
browserHistory is not defined

### ISSUE THREAD

**Issue by h2s20** [studiointeract/accounts-ui#102]
I am working with react-router and on login or logout I get the following error in the browser console:
Exception in setTimeout callback: ReferenceError: browserHistory is not defined at http://localhost:3000/packages/std_accounts-ui.js

The problem may be the first line in helpers.js
`try { import { browserHistory } from 'react-router'; } catch(e) {}`

On research I found the following on https://hacks.mozilla.org/2015/08/es6-in-depth-modules/:

> There is no error recovery for import errors. An app may have hundreds of modules in it, and if anything fails to load or link, nothing runs. You can’t import in a try/catch block. (The upside here is that because the system is so static, webpack can detect those errors for you at compile time.)

If I remove the try/catch around the import everything works fine.

**Comment by stolinski** [comment]
+1

**Comment by comus** [comment]
may be use require instead
```
let browserHistory
try {
  browserHistory = require('react-router').browserHistory
} catch (e) {}
```

**Comment by PeterMerkert** [comment]
When will it be merge?

**Comment by timbrandin** [comment]
It is merged! ;D
