### ISSUE TITLE
Typo breaking requestPermissions in Accounts.ui.config (1.2.23)

### ISSUE THREAD

**Issue by jrtilson** [studiointeract/accounts-ui#126]
There's a [typo here](https://github.com/studiointeract/accounts-ui/blob/master/imports/accounts_ui.js#L101) that's throwing `ReferenceError: scope is not defined` to the console when you supply requestPermissions in Accounts.ui.config, ie:

```
Accounts.ui.config({
  passwordSignupFields: 'USERNAME_AND_EMAIL',
  requestOfflineToken: { google: true },
  loginPath: '/login',
  requestPermissions: {
    google: ['https://www.googleapis.com/auth/userinfo.email'],
  },
});
```

**Comment by santiagorp** [comment]
Any idea when this typo going to be fixed?
