### ISSUE TITLE
withTracker instead of createContainer on LoginForm.jsx (React16.0 support)

### ISSUE THREAD

**Issue by kkazene** [studiointeract/accounts-ui#131]
Hey, it seems this package is still using `createContainer` [here](https://github.com/studiointeract/accounts-ui/blob/master/imports/ui/components/LoginForm.jsx), and I'm getting warnings that this function was deprecated in `react-meteor-data@0.2.13`. Could this be changed to use the `withTracker`-function instead?

**Comment by gsc-dev** [comment]
+1 very simple change

https://github.com/meteor/react-packages/tree/devel/packages/react-meteor-data

**Comment by afranche** [comment]
+1, There is a PR for this issue -> #130

**Comment by javascriptlove** [comment]
@timbrandin sorry to ping, is it possible to upgrade the package with the aforementioned PR?

**Comment by jameschetwood** [comment]
Subscribing

**Comment by lukelarsen** [comment]
I need this as well. Any chance that PR can go in?
