### ISSUE TITLE
Need to remove indirect dependency on Blaze

### ISSUE THREAD

**Issue by jshimko** [studiointeract/accounts-ui#15]
Looks like `softwarerero:accounts-t9n` has a dependency on Blaze.  Without it installed, I get this...

`Uncaught ReferenceError: UI is not defined     softwarerero_accounts-t9n.js?hash=96cfc39…:34 `

https://github.com/softwarerero/meteor-accounts-t9n/blob/master/package.js#L24

**Comment by timbrandin** [comment]
oh noo, I have to push this upstream to T9n, I don't want to fork the translations.

**Comment by ArthurPai** [comment]
I found in your package.js have followed line

`api.imply('softwarerero:accounts-t9n@0.0.20');`

maybe this line causes the ReferenceError.

beacuse in T9n version 0.0.20 is using UI.registerHelper('t9n', .......) to register itself

**Comment by timbrandin** [comment]
Alright, thx, I'm curious how we can overcome this without loosing the benefits of lots of existing translations.

**Comment by timbrandin** [comment]
This release seem to work much better without blaze-html-templates:
https://github.com/studiointeract/accounts-ui/releases/tag/release-1.1.7
