### ISSUE TITLE
Accounts.onCreateUser issue

### ISSUE THREAD

**Issue by SachaG** [studiointeract/accounts-ui#17]
You can only have a single callback hook on `Accounts.onCreateUser`, which leads to the following warning:

```
You've implemented Accounts.onCreateUser elsewhere in your application, you can therefor not use Accounts.ui.config({ onPostSignUpHook }) on the server.
```

What if instead of showing that warning, `accounts-ui` simply extended the current callback (available at `Accounts._onCreateUserHook`) with its own custom logic?

i.e.

```js
Accounts.onCreateUser(() => {
  Accounts._onCreateUserHook();
  // do custom stuff here
}
```

**Comment by timbrandin** [comment]
You mean this?
https://github.com/studiointeract/accounts-ui/blob/master/imports/api/server/onPostSignUpHook.js#L1

**Comment by SachaG** [comment]
Yeah either one these three solutions (only warn if the hook if used, run both the hook and the original callback, fix the problem at the root) works for me, since I'm not using the hook anyway :)

**Comment by timbrandin** [comment]
Alright, would it be a big issue if removed the serverside version of the hook? Just now it's causing more issues than it is solving, when one already can use onCreateUser for the same thing, maybe just document how to do this in the Readme without and then remove the hook?

**Comment by SachaG** [comment]
Sounds good to me.

**Comment by timbrandin** [comment]
https://github.com/studiointeract/accounts-ui/releases/tag/release-1.1.6
