### ISSUE TITLE
unexpected reload

### ISSUE THREAD

**Issue by radzom** [studiointeract/accounts-ui#18]
when trying to log in (pressing sign in button or hitting enter) a page reload is made with the same url but a "?" is added. This happens on any page including the LoginForm.

I tried commenting out all customized configuration

```
import { Accounts } from 'meteor/std:accounts-ui';

export default function () {
  Accounts.ui.config({
    passwordSignupFields: 'USERNAME_AND_EMAIL',
    // loginPath: '/login',
    // signUpPath: '/register',
    // resetPasswordPath: '/reset-password',
    // profilePath: '/profile',
    // onSignedInHook: () => FlowRouter.go('/dashboard'),
    // onSignedOutHook: () => FlowRouter.go('/'),
    // minimumPasswordLength: 6
  });
}

```

using default Accounts.ui.LoginForm but it does not help.
The problems started in 1.1.4 
I have gone back to version 1.1.0 
:-(

**Comment by timbrandin** [comment]
Alright, seems like I can reproduce it. The form is submitted before we can stop it.

**Comment by timbrandin** [comment]
This should solve that issue: https://github.com/studiointeract/accounts-ui/releases/tag/release-1.1.10
