### ISSUE TITLE
The app will crash if go to any accounts relation routers when the user already logged in

### ISSUE THREAD

**Issue by ArthurPai** [studiointeract/accounts-ui#19]
The app will crash if go to any accounts relation routers when the user already logged in,
like /login, /signup, /reset-password, /profile.

I found in LoginForm.jsx is using `(user && formState == STATES.PROFILE && (user && 'password' in user.services))` to add changePassword button,

But the app will crach in the `user.services` is undefined.
`LoginForm.jsx:287 Uncaught TypeError: Cannot use 'in' operator to search for 'password' in undefined`

In the Meteor guild, the user services field will not auto send to client,
is it correct using `user.services` is client side?

**Comment by timbrandin** [comment]
I've fixed this in 3e7f6d3c4d020461657a129e2ca42bb0702b35bb, try updating to the latest release `1.1.10`
