### ISSUE TITLE
Add chinese language for China

### ISSUE THREAD

**Issue by ArthurPai** [studiointeract/accounts-ui#20]
China 

zh_cn.js
```
T9n.map('zh_cn', {
  cancel: '取消',
  'Enter password': '输入密码',
  'Enter newPassword': '输入新密码',
  'Enter email': '输入电子邮箱',
  'Enter username': '输入用户名',
  'Enter username or email': '输入用户名或电子邮箱',
  error: {
    accounts: {
      'Invalid email or username': '无效的密码或用户名',
      'Internal server error': '内部服务器错误',
      'undefined': '服务未配置',
    },
  },
  'or use': '或是使用',
});
```

**Comment by timbrandin** [comment]
We're moving the translations to [softwarerero:accounts-t9n](https://github.com/softwarerero/meteor-accounts-t9n), could you please PR over there, it's just a matter of changing the existing files, I'll release those as fast there's a new release.

**Comment by ArthurPai** [comment]
I am PR zh_cn and zh_tw to [softwarerero:accounts-t9n], wait he merge

**Comment by timbrandin** [comment]
awesome, give me a hint or PR when to update. I love that Bootstrap PR you made, gonna give it a go later tonight.

**Comment by ArthurPai** [comment]
Ok, I will send PR when t9n update.
