### ISSUE TITLE
accounts-meteor-developer not working

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#26]
Error: `LoginForm.jsx:512 Uncaught TypeError: login is not a function`

I guess that the bug is that the service is defined as `meteor-developer`, but it needs to be `MeteorDeveloperAccount` (ref: http://docs.meteor.com/#/full/meteor_loginwithexternalservice)

**Comment by PolGuixe** [comment]
The meteor service requires special treatment, see: https://github.com/meteor-useraccounts/core/blob/37fde86da5eeee33465fd05a2c5dccb3fe16fed9/lib/templates_helpers/at_social.js#L75

**Comment by PolGuixe** [comment]
Created PR https://github.com/studiointeract/accounts-ui/pull/28

**Comment by timbrandin** [comment]
Perfect, merged!
