### ISSUE TITLE
Improvements for 3rd party services.

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#27]
When only using 3rd party services, there are few things that could be improved. e.g.:
- Not showing the `Forget Password Button`
- Not showing the `Login / Register Buttons`

**Comment by timbrandin** [comment]
This sounds like a bug, could you check this @maz-dev ? :dancer:

**Comment by timbrandin** [comment]
I'm not sure we still have this issue, closing for now.

**Comment by alliejc** [comment]
I am still having this issue. Ideally, I would be able to limit my users to only logging in with Pinterest (or any third party), instead of also giving the e-mail/password etc options.

![screen shot 2017-03-26 at 1 10 13 pm](https://cloud.githubusercontent.com/assets/10934426/24334779/9653870a-1225-11e7-8f6e-25b6d3d9efef.png)

**Comment by PolGuixe** [comment]
If you eliminate the `accounts-password` package you should only see the other 3rd party login services. 

However I can still see the `Forgot your password?` button. 

<img width="602" alt="screen shot 2017-03-28 at 20 03 45" src="https://cloud.githubusercontent.com/assets/6626225/24432728/161dd21a-13f2-11e7-8122-b14ff276aa0d.png">


Maybe is because [here](https://github.com/studiointeract/accounts-ui/blob/master/imports/ui/components/LoginForm.jsx), ` showForgotPasswordLink()` doesn't check `hasPasswordService()` :
```
// LoginForm.jsx
...
  showForgotPasswordLink() {
    return !this.state.user
      && this.state.formState == STATES.SIGN_IN
      && _.contains(
        ["USERNAME_AND_EMAIL", "USERNAME_AND_OPTIONAL_EMAIL", "EMAIL_ONLY"],
        passwordSignupFields());
  }
...
...
    if (this.showForgotPasswordLink()) {
      loginButtons.push({
        id: 'switchToPasswordReset',
        label: T9n.get('forgotPassword'),
        type: 'link',
        href: resetPasswordPath,
        onClick: this.switchToPasswordReset.bind(this)
      });
    }
...
```
