### ISSUE TITLE
Does accounts-ui require tracker-component?

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#29]
Since I updated from 1.1.13 to 1.1.15 (and meteor to 1.3.1), the `tmeasday:check-npm-versions` package was added.

```
updated to Meteor 1.3.1.          
                                                                                
Changes to your project's package version selections from updating package
versions:
                                              
std:accounts-basic           upgraded from 1.1.8 to 1.1.9
std:accounts-ui              upgraded from 1.1.13 to 1.1.15
tmeasday:check-npm-versions  added, version 0.1.1
```
And an error appeared to my console browser:
`Uncaught Error: tracker-component@^1.3.13 not installed.`

The package is actually installed in `node_modules`. Is this a `tmeasday:check-npm-versions` or meteor 1.3.1 bug?

**Comment by xavcz** [comment]
Same for me with the same config

**Comment by KaurKirikall** [comment]
+1

**Comment by tdhz77** [comment]
+1

**Comment by timbrandin** [comment]
Strange, I thought npm packages got installed automatically with meteor 1.3, I move to npm might be worthwhile.

**Comment by timbrandin** [comment]
Though the simple solution is to `npm i --save tracker-component`

**Comment by PolGuixe** [comment]
The package is actually installed in `node_modules`. But before the package `tmeasday:check-npm-versions`, wasn't added. Hence not doing the verification. Now when it does the check, it fails and it throws the error. 

Probably is worth checking this issue: https://github.com/tmeasday/check-npm-versions/issues/1 as the problem may be related to this package.

**Comment by PolGuixe** [comment]
@timbrandin I've tried to manually install the package but it was already installed.

**Comment by timbrandin** [comment]
I guess we could just remove that package as it is causing more than it is solving right now.

**Comment by tmeasday** [comment]
Try bumping the version of `check-npm-versions`?

**Comment by timbrandin** [comment]
Cool, seems to work well with fresh install och 1.3.1:
Steps followed:
1. `meteor create test --release 1.3.1`
2. `meteor add std:accounts-ui`
3. `meteor`

Warnings are throwed (good!)

4. `npm i --save tracker-component react react-dom`
5. `meteor`

No warnings, and app running with no errors in server/client.

Published `1.1.16`, will propagate these changes down to basic and semantic immediately.

**Comment by JeremyIglehart** [comment]
I just ran into this problem myself using the version available from meteor atmosphere... Uninstalling . that, and then manually cloning this git repository into `/packages` and then running `meteor add std:accounts-ui` worked like a charm.

**Comment by timbrandin** [comment]
@JeremyIglehart did you use the `devel` version or `master`?
