### ISSUE TITLE
Tracker is not defined

### ISSUE THREAD

**Issue by firrae** [studiointeract/accounts-ui#31]
I notice that this package at version 1.1.17, when used with the latest tracker-component errors out as so by @jshimko here: https://github.com/studiointeract/tracker-component/issues/6#issuecomment-208681239

Could we get some clarification on if this is a bug, or if this now requires us to use your NPM Tracker package?

**Comment by firrae** [comment]
The following errors are also appearing in the browser console after downgrading accounts-ui to 1.1.16 and having the latest tracker-component:
```
Uncaught Error: Cannot find module 'tracker-component/package.json'
Uncaught Error: Cannot find module 'meteor/std:accounts-ui'
```

**Comment by timbrandin** [comment]
There's a solution for this in `v.1.1.18`, related: https://github.com/studiointeract/tracker-component/issues/6
