### ISSUE TITLE
Do not use package.json if it's not a npm package!!!

### ISSUE THREAD

**Issue by JWo1F** [studiointeract/accounts-ui#35]
When you use package.json with dependencies we have two copies of all your packages (one is my plus one is your). It's very bad!

It's crazy, but you use package.json for add of your sub-packages (bootstrap, etc.). Then we have three(!) copies of react, three copies of react-dom and three copies of tracker-component!

**Comment by timbrandin** [comment]
@JWo1F I'm not sure what's the problem, should we switch to peerDependencies instead for the NPM dependencies. We will soon transition fully to NPM so I don't think we will remove it anytime soon.

**Comment by timbrandin** [comment]
We need to use package.json for Meteor 1.3 and our npm dependencies at the moment, when we can transition to fully to the npm registry this will also come in hand having most of the legwork done.
