### ISSUE TITLE
After updating to Meteor 1.3.2.4 and  std:accounts-ui 1.1.20 Login is impossible

### ISSUE THREAD

**Issue by capensisma** [studiointeract/accounts-ui#36]
Hi after updating to the last version here and the last version of meteor it won't work at all 

I cannot login or whatever

`std:accounts-ui    upgraded from 1.1.12 to 1.1.20`
`updated to Meteor 1.3.2.4. `

Try it with a new install please :)

**Comment by justintime4tea** [comment]
I also am unable to login via social networks using std:accounts-ui after updating Meteor to 1.3.2.4.

I have not tested older versions but this wasn't the case until recently. Regular account login seems to work (local user accounts, not social network login)

**Comment by capensisma** [comment]
@justintime4tea too slow bro I found the bug before ya ;) :D

**Comment by justintime4tea** [comment]
Exactly, hence why I posted a comment here and didn't open a new issue ;)

**Comment by capensisma** [comment]
@justintime4tea did you fix this?

**Comment by timbrandin** [comment]
@maz-dev do you want to take this, or should I?

**Comment by jaysig** [comment]
Any updates on getting the social buttons fixed?

**Comment by timbrandin** [comment]
I'm looking at this, and I've got it working in React Ionic, though I still get a weird redirect to `/facebook`. I'm not sure if that is something that can be traced down to accounts-ui, but I'm on it.

**Comment by timbrandin** [comment]
@jaysig could you explain what issue you are experiencing?
