### ISSUE TITLE
Examples give incorrect passwordSignupFields values

### ISSUE THREAD

**Issue by justintime4tea** [studiointeract/accounts-ui#38]
NO_PASSWORD is not a valid option according to your documentation yet examples use it and say it is the default.

Earlier in documentation (near top) it states that EMAIL_ONLY_NO_PASSWORD is the default.

and in code:

```
if (options.passwordSignupFields) {
    if (_.contains([
      "USERNAME_AND_EMAIL",
      "USERNAME_AND_OPTIONAL_EMAIL",
      "USERNAME_ONLY",
      "EMAIL_ONLY",
      "EMAIL_ONLY_NO_PASSWORD",
      "USERNAME_AND_EMAIL_NO_PASSWORD"
    ],
```

**Comment by timbrandin** [comment]
Awesome! Thx for noticing! 👍
