### ISSUE TITLE
Support for oAuth providers (Twitter, FB, etc.)

### ISSUE THREAD

**Issue by SachaG** [studiointeract/accounts-ui#4]
What would be the steps to add support for other log in providers?

**Comment by timbrandin** [comment]
Yeah, I'm on it, do we want them before them before the fields in the Form?

**Comment by timbrandin** [comment]
Have to look a little more on this, I know how to do it, but it will take more than an hour tonight.

**Comment by maz-dev** [comment]
I'm working on it right now. I'll let you know the progress tomorrow, but it shouldn't take too long.

**Comment by queso** [comment]
Nice. I have some sample code if someone wants it.

**Comment by timbrandin** [comment]
We've started work on this in the devel branch today.

**Comment by queso** [comment]
Here is the sample stuff I have: https://gist.github.com/queso/edf51344173be4923c65dbe033b5f445

**Comment by queso** [comment]
I also think @maz-dev was close to having a PR ready, you two should talk in the spacedojo slack.

**Comment by timbrandin** [comment]
@queso yeah @maz-dev's work is already in devel now, you can try it out on `1.0.21-rc.1`

**Comment by timbrandin** [comment]
We do support this now, and we're working on adding a configuration gui for the services.
