### ISSUE TITLE
Accounts.sendLoginEmail does not work if address is set

### ISSUE THREAD

**Issue by pfuerholz** [studiointeract/accounts-ui#42]
If parameter 'address' is set email's 'to'-address will not be set:

'To' is set with variable 'email':
`  var options = {
    to: email,
    from: Accounts.em`

But 'email' is only set when address is not set:
`  if (!address) {
    var email = _.find(user.emails || [],
                       function (e) { return !e.verified; });
    address = (email || {}).address;
  }`

This case happens when configuring 'EMAIL_ONLY_NO_PASSWORD':
`  Accounts.ui.config({
	passwordSignupFields: 'EMAIL_ONLY_NO_PASSWORD',
        ...
`
- Did I miss something?
- Please tell me if you'd like a pull request.

**Comment by timbrandin** [comment]
Good catch, we should probably send to address instead of email: 508aff3eed

**Comment by timbrandin** [comment]
I've pushed a fix for this in `1.2.3`, could you verify that it works?

**Comment by pfuerholz** [comment]
Works for my use case. Thanks!
