### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#44]
I think that we should add more error messages such as: 
- _This email doesn't exist_:  sign in with unregistered email. 
- _This email already exist_:  sign up with an already used email.
- _This password is incorrect_: sign in with an incorrect password.

Are any hooks that can be used?

**Comment by jaysig** [comment]
The main reason you would want to avoid that, is it opens up your site to brute force hacking. If someone can find a correct email, they can create a dictionary attack to try and guess your password.

**Comment by PolGuixe** [comment]
Clear... not even: 
- These email or password are incorrect

¿?

**Comment by timbrandin** [comment]
We get all the error messages from this package so if you want to change them right now I suggest adding a PR overthere, because we also want them translated.
https://github.com/softwarerero/meteor-accounts-t9n

**Comment by PolGuixe** [comment]
I am not getting any error message when I am putting the a not registered email or wrong password when signing up. Although those messages appear in https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/en.coffee. 

When I submit the `Sign In` with wrong information it just reloads with no error message at all. Is it the normal behaviour of the package?

**Comment by timbrandin** [comment]
Closing this due to security issues.
