### ISSUE TITLE
STUDIO INTERACT, PLEASE RESPOND. Need Docs on Social Buttons, Template Mods

### ISSUE THREAD

**Issue by VikR0001** [studiointeract/accounts-ui#48]
I'm dead in the water with accounts for the past 3 days, waiting for a response to my previous post here. 

I need to install social buttons. Is that possible? The Read.me doesn't say how to do it. How is this done?

I also need documentation on how to modify the components. Do I overwrite the ones included in the package? Wouldn't my mods be deleted when the package is updated? Please explain how this is done or provide a link that discusses how this is done.

**Comment by jshimko** [comment]
I can't speak to the social buttons part, but you can see any of the UI add-on packages (Bootstrap, etc) for examples of customizing the templates.  You could start by just cloning the [Bootstrap package](https://github.com/studiointeract/accounts-bootstrap) into your `/packages` folder and changing whatever you need in the components.

**Comment by VikR0001** [comment]
Very good. Do I directly edit the components in the package? Won't my edits be deleted next time the package is updated?

**Comment by jshimko** [comment]
No.  You're not using the official package at that point.  You're using your edited copy of it.  Ideally, you should also change the name of the package to something more specific to you (instead of `std:accounts-bootstrap`, maybe just `accounts-ui-custom`).  Then install it with meteor add `accounts-ui-custom`.

**Comment by VikR0001** [comment]
If I go to `~/.meteor/packages`, I see the package `std_accounts-material`, which I've previously downloaded. However, it only contains an alias. So I need to learn:

- Exactly what folder to duplicate and where to put it
- How to get meteor add to see it 
- How to get accounts-ui to load it

I've just googled:

> how to modify a meteor package

There are a lot of results. I will read further to find out how to do this.

Thanks very much for this info!
