### ISSUE TITLE
defaults for onResetPasswordHook and onEnrollAccountHook prevent showing correct form

### ISSUE THREAD

**Issue by todda00** [studiointeract/accounts-ui#53]
The current default functions for onResetPasswordHook and onEnrollAccountHook redirect the form to the loginPath, which then changes the formState from PASSWORD_CHANGE to SIGN_IN and does not show the correct change password form. 

In my project I set these hooks to blank functions to make these functions work, but this seems like a bad default.

**Comment by timbrandin** [comment]
Is this still an issue to you? :)

**Comment by todda00** [comment]
Seems to be not an issue anymore, thanks!
