### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by SachaG** [studiointeract/accounts-ui#56]
As you can see, some translations are missing when using [meteor-accounts-t9n](https://github.com/softwarerero/meteor-accounts-t9n):

![https://s3.amazonaws.com/f.cl.ly/items/093D0B0q0K1K2E162C1T/Screen%20Shot%202016-06-10%20at%2010.14.15%20AM.png?v=cfe8c7c2](https://s3.amazonaws.com/f.cl.ly/items/093D0B0q0K1K2E162C1T/Screen%20Shot%202016-06-10%20at%2010.14.15%20AM.png?v=cfe8c7c2)

What's the best way to add them in? Make a PR to accounts-t9n? Or is there somewhere in this repo where I could translate them?

**Comment by timbrandin** [comment]
These are new to accounts-t9n actually, I don't think people have noticed they are missing from most languages, so they need a push for all authors to translate the missing pieces from the english file:
https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/en.coffee

**Comment by timbrandin** [comment]
I'm closing this as this can be resolved with a push on https://github.com/softwarerero/meteor-accounts-t9n for now.
