### ISSUE TITLE
Theme for Material-ui (The real from callemall. Not materialize)

### ISSUE THREAD

**Issue by hmontes** [studiointeract/accounts-ui#63]
Hi. I try to make a theme for https://github.com/callemall/material-ui but i don't understand your instructions.

Do you have some examples for the changes? I don't understand your instructions (I'm a newbie in javascript).

Thanks and congratulations for your plugin

**Comment by rhyslbw** [comment]
Have you tried using the Materialize package as a starting point? Should be fairly trivial to swap out the html with components from Material UI.

**Comment by Captain-GaDo** [comment]
Yes. I tried but i don't understand how i can make these changes.

Probably is my mistake because i'm a beginner in Javascript. But do you have a more simple guide?

**Comment by rhyslbw** [comment]
I only came across this yesterday so am pretty fresh with the codebase. I only know about what's documented and from skimming the materialize adaptor, but decided to shelve this until it's more stable. Mainly https://github.com/studiointeract/accounts-ui/issues/60 is a blocker for me, but if you put some code up I can assist you

**Comment by lawrentiy** [comment]
You can use parts of my code.
https://github.com/lawrentiy/accounts-material/commit/650f29b751913e5439b459d9c5d8b2d1b5b69f72#diff-5a82d163aa6ac406a2219cef65f60760

It`s not clean. But the main part - redefinition for Button, Field, Field classes.

I added some logic for login using phone, but I have no time to cut it from main.jsx.

Welcome for questions!

**Comment by PolGuixe** [comment]
I just created a package that uses `callemall/material-ui`. 

You can check it here: https://atmospherejs.com/zetoff/accounts-material-ui

It would be great if you can test it and suggest improvement. So far it works for all my cases.

**Comment by PolGuixe** [comment]
@timbrandin could you add this one: https://atmospherejs.com/zetoff/accounts-material-ui
to the list of packages?

**Comment by rhyslbw** [comment]
@PolGuixe Will test soon. To add your package to the list just submit a PR and then @timbrandin can just merge in

**Comment by timbrandin** [comment]
This seems to be linked already! great work!
