### ISSUE TITLE
Install gets stuck

### ISSUE THREAD

**Issue by haltyl** [studiointeract/accounts-ui#67]
For some reason, I can’t seem to finish the installation. When I enter “meteor add std:accounts-ui” it downloads and loads various things, but it gets stuck at this point: “Extracting std:accounts-ui@1.2.6...”

Any idea about what I’m doing wrong, or how I can fix it?
The machine is running Windows 7.

**Comment by u-abramchuk** [comment]
The same here. 

Win 10 Pro

**Comment by haltyl** [comment]
And you have found no solution to the problem?

**Comment by Batistleman** [comment]
seems to be related to this: https://github.com/meteor/meteor/issues/7688

**Comment by haltyl** [comment]
@Batistleman Thanks for the link.

I can now install it. I'm unsure of what fixed the error. But here is what I did:
I installed 7-zip, as recommended in the other posts.
After er reboot, install still got stuck.
I opened task manager and found the process "7zip.exe". Located the exe-file and killed the process.
Then I renamed the exe-file and ran the install again.
This time with success.

**Comment by tetiogit** [comment]
@haltyl I've followed your suggestion, I've killed the process from the task-manager. 
However I've not understood the meaning of "Located the exe-file and killed the process".
As a result, after killing the process I've received another error: 

Error: ENOENT: no such file or directory, open 'C:\Users\USERNAME~1.CAT\AppData\Local\Temp\mt-ifhfba\os.json' at Error (native)

It seems that it does not recognize the user folder.

**Comment by haltyl** [comment]
@tetiogit What I meant with "Located the exe-file and killed the process" is this: I killed the process with the 7zip.exe-file, and then renamed that same file.
If you right click on the process and choose properties you will be able to see the exact location of the file. Then go to the location and rename it. That is what I did, and it worked for me.

**Comment by tetiogit** [comment]
It worked for me! I had to install coffeescritp (meteor add coffeescript) which was not installed before and let a second crash coming out, but now everything is fine.

**Comment by pgiani** [comment]
Here is my solution download the 32bit version of 7Zip and install it

copy the file:
 7z.exe 

from:
C:\Program Files (x86)\7-Zip\

And replace it where meteor has its version ( while meteor add is running open TaskManager right click on the 7z.exe file under Bacground processes  then choose open file location), in my case the path is:

C:\Users\--- YOUR USER NAME ---\AppData\Local\.meteor\packages\meteor-tool\1.4.2_1\mt-os.windows.x86_32\dev_bundle\bin

stop meteor them
meteor add std:accounts-bootstrap

installation now works

**Comment by igor90007** [comment]
win 10. I fixed:
in \AppData\Local\.meteor\packages\meteor-tool\1.4.2_3\mt-os.windows.x86_32\dev_bundle\bin
should delete 7z.exe

**Comment by timbrandin** [comment]
This does not seem related to the code in this project, closing for now.

**Comment by fsolarv** [comment]
How I fix it: (Windows 10)
1. Go to: C:\Users\<youruser>\AppData\Local\.meteor\packages\meteor-tool\
2. select your current meteor version folder (1.4.2_3 in my case)
3. go to: \mt-os.windows.x86_32\dev_bundle\bin
4. rename 7z.exe to whathever.exe
5. Done

**Comment by timbrandin** [comment]
Perfect! Yeah, I can to confirm this works, but it is an issue with meteor not with this package. Theres a long ongoing issue over there.

Also works to just remove it, if you're running  windows 10 64bits.

**Comment by fsolarv** [comment]
Seems to be fixed with the new meteor update (v1.4.2.5) , they update the 7z.exe to a newer version and now works fine and faster. Windows 10 64bits too.

**Comment by timbrandin** [comment]
Ah great!! Thx for the info

Skickat från min iPhone
