### ISSUE TITLE
Redirect with React Router on onSignedInHook or onSignedOutHook?

### ISSUE THREAD

**Issue by meteorplus** [studiointeract/accounts-ui#79]
Hello
Currently we are using FlowRouter on 

```Accounts.ui.config({
  passwordSignupFields: 'EMAIL_ONLY',
  loginPath: '/login',
  signUpPath: '/signup',
  resetPasswordPath: '/reset-password',
  profilePath: '/profile',
  onSignedInHook: () => FlowRouter.go('/general'),//here?? usually we could have a this.context.router but here don't!
  onSignedOutHook: () => FlowRouter.go('/login'),
  minimumPasswordLength: 6
});
```

usually we could have a this.context.router but here don't!??

**Comment by SachaG** [comment]
How about passing all these options as props to the components instead of defining them in a separate object?

**Comment by timbrandin** [comment]
I totally agree, the options array feels obsolete

**Comment by timbrandin** [comment]
That would also simplify the code

**Comment by meteorplus** [comment]
So can we have access to the props or the context within the Accounts component ?
thanks :)

**Comment by timbrandin** [comment]
Anyhow, this should be solved now.
