### ISSUE TITLE
Feature-request: support for i18n

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#81]
T9n is great, but I am using i18n in my project and having two translation systems is a bit cumbersome. 

What do you think?

**Comment by pozylon** [comment]
T9n is an implementation of i18n (= simply means https://en.wikipedia.org/wiki/Internationalization_and_localization )

**Comment by SachaG** [comment]
I think @PolGuixe is talking about https://github.com/yahoo/react-intl specifically.

**Comment by PolGuixe** [comment]
I was thinking about https://github.com/vazco/meteor-universe-i18n because I didn't knew about 
https://github.com/yahoo/react-intl :)

**Comment by pozylon** [comment]
So actually the solution could be:
- phase out dependency of accounts-t9n.
- introduce an accounts-ui internal dictionary for all language/locale dependent parts
- use the same keys as t9n so if you use t9n-accounts you could simply do: Accounts.ui.texts = T9n.maps[T9n.getLanguage()] (should be tracker enabled) to have a localized accounts ui.

That would allow us to potentially use any localization package for translation.

**Comment by timbrandin** [comment]
I'd love to see a transition to i18next or similar, where one could import the language on needs on demand from the package. But I think this should first be solved in accounts-t9n as suggested by @PolGuixe

**Comment by timbrandin** [comment]
Feel free to take this on @pozylon :)
