### ISSUE TITLE
Invalid Key: on example

### ISSUE THREAD

**Issue by grinono** [studiointeract/accounts-ui#87]
When running your example in client site:

```
Accounts.ui.config({
  passwordSignupFields: 'EMAIL_ONLY',
  loginPath: '/',
  signUpPath: '/',
  resetPasswordPath: '/',
  profilePath: '/',
  onSignedInHook: () => FlowRouter.go('/general'),
  onSignedOutHook: () => FlowRouter.go('/login'),
  minimumPasswordLength: 6
});

```

the following Error got returned.

`Uncaught Error: Accounts.ui.config: Invalid key: loginPath`

it's not loginPath based as all the other options give the same result.
i'm on: std:accounts-ui@1.2.10

**Comment by timbrandin** [comment]
I'm having trouble reproducing this, is there any other parameter in your app that I'm missing?

**Comment by JohnAllen** [comment]
I'm getting this too for the following three but not `passwordSignupFields`.

```
loginPath: '/login',
  signUpPath: '/signup',
  requireEmailVerification: true,
```

Are the two of us really the only ones to get it?

**Comment by yanickrochon** [comment]
Same issue. The value is in the code, but the module complaints about it.

**Comment by yanickrochon** [comment]
EDIT: disregard, I was using `Accounts.config` and not `Accounts.ui.config`.
