### ISSUE TITLE
localStorage not defined in server side

### ISSUE THREAD

**Issue by comus** [studiointeract/accounts-ui#89]
when doing SSR,  it shows error:

error while server-rendering' 'ReferenceError: localStorage is not defined\n    at LoginForm.getDefaultFieldValues (packages/std:accounts-ui/imports/ui/components/LoginForm.jsx:443:9)

may be add more check in LoginForm
`typeof localStorage === 'undefined'`

**Comment by timbrandin** [comment]
Ah, yeah, I haven't done a lot to make this work great in SSR. Would you mind creating a PR that checks this?

**Comment by timbrandin** [comment]
Great work @comus, this is now in the released version `1.2.15`.
