### ISSUE TITLE
Investigate possibility to publish on npm

### ISSUE THREAD

**Issue by radzom** [studiointeract/accounts-ui#9]
Hi, I am using this in the [mantra-sample-app](https://github.com/mantrajs/mantra-sample-blog-app).
And when writing a test for it i get the error:

> Error: Cannot find module 'meteor/std-accounts-ui
>    at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
> ...

The app works fine. I did run the command meteor add std-accounts-ui

So my guess is the unit testing (mocha) has problems with atmosphere packages and i would like to test it with npm package instead.

**Comment by timbrandin** [comment]
oh, sorry, I'm changing the name of the package from `studiointeract:react-accounts-ui` to `std:accounts-ui` – will publish this today.

**Comment by timbrandin** [comment]
Sorry, for the temporary faulty documentation, this should be fixed now.

**Comment by radzom** [comment]
What i meant was - Can you please publish it to npmjs.org?

**Comment by timbrandin** [comment]
This package is quite dependant on Meteor packages at the moment, I'm not sure if publishing it to npmjs at the moment would benefit users much, even though I'd love to do that right now the community will soon enough transition to an npm based package system.

You can read more on this in the forums, here's an example:
https://forums.meteor.com/t/request-publish-tracker-on-npm/20571

**Comment by timbrandin** [comment]
Maybe related discussion:
https://forums.meteor.com/t/proposal-make-it-easier-to-publish-on-npm-with-a-prepublish-command/20627

**Comment by timbrandin** [comment]
I'll put up a goal for this when we have a timeline for easier getting meteor packages up on npm, which is an ongoing topic atm on the forums (as mentioned above).

**Comment by timbrandin** [comment]
This is still an ongoing topic, and most internal packages in Meteor has still not moved to npm.
