### ISSUE TITLE
Cannot find module 'tracker-component/package.json'

### ISSUE THREAD

**Issue by elegos** [studiointeract/accounts-ui#90]
Hello!

I'm trying out `std:accounts-ui` with `accounts-password` installing `tracker-component` via `meteor npm i --save tracker-component`.

The problem is that I've got two errors, using the `<Accounts.ui.LoginForm />` component:

1. `Cannot find module 'tracker-component/package.json'` (actually it exists under node_modules)
2. `Error: getNodeFromInstance: Invalid argument.`

This is my config:

    import { Accounts } from 'meteor/std:accounts-ui'

    Accounts.config({
        sendVerificationEmail: false
    })

    Accounts.ui.config({
        passwordSignupFields: 'USERNAME_ONLY',
    })

Meteor: 1.4.2.3
std:accounts-ui:  1.1.15
accounts-password: 1.1.13

EDIT: nvm, dunno why it installed an old version of std:accounts-ui?!? Installed as usual via `meteor add std:accounts-ui`

**Comment by timbrandin** [comment]
I guess it's time to replace tracker-component with meteor's createComponent, what are your thoughts @PolGuixe ?

**Comment by PolGuixe** [comment]
@timbrandin I am not aware of Meteor's createComponent, and with a quick search I couldn't find any documentation. Removing tracker-component seems a major refactor.

**Comment by timbrandin** [comment]
Yeah, the package is called meteor-react-data and it's more used by now with meteor.
